# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a81d03fe9cc6032e758d10905c998e26cb53da384184ff4e9ecbd6b853e539338c198813bb56334b39304140bc605802a269a589fc85efa0d2a25af90c08b0c

test:
  secret_key_base: 85e3beda94a611fc3c92f0b16b8e7a5675d7efc50ae8f12c2eeebef3ca870fb6d57d508e2276a70ed425bc491ea74c22512d4194d0612c898132123408b42ec4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
